export const examples = [
  {
    descripcion: 'Invierte los bits de un número binario',
    estados: [
      { nombre: 'q0', id: 0 },
      { nombre: 'q1', id: 1 },
    ],
    alfabeto: ['0', '1'],
    blanco: '△',
    estadoFinal: { nombre: 'q1', id: 1 },
    transiciones: [
      {
        id: 0,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q0', id: 0 },
        leer: '0',
        escribir: '1',
        direccion: 'R',
      },
      {
        id: 1,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q0', id: 0 },
        leer: '1',
        escribir: '0',
        direccion: 'R',
      },
      {
        id: 2,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '△',
        escribir: '△',
        direccion: 'R',
      },
    ],
    estadoInicial: { nombre: 'q0', id: 0 },
  },
  {
    descripcion: "Complementa una cadena de 0's y 1's, y regresa a la posición inicial",
    estados: [
      { nombre: 'q0', id: 0 },
      { nombre: 'q1', id: 1 },
      { nombre: 'q2', id: 2 },
      { nombre: 'qf', id: 3 },
    ],
    alfabeto: ['0', '1'],
    blanco: '△',
    estadoFinal: { nombre: 'qf', id: 3 },
    estadoInicial: { nombre: 'q0', id: 0 },
    transiciones: [
      {
        id: 0,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '0',
        escribir: '#',
        direccion: 'R',
      },
      {
        id: 1,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '1',
        escribir: '#',
        direccion: 'R',
      },
      {
        id: 2,
        desde: { nombre: 'q1', id: 1 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '0',
        escribir: '1',
        direccion: 'R',
      },
      {
        id: 3,
        desde: { nombre: 'q1', id: 1 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '1',
        escribir: '0',
        direccion: 'R',
      },
      {
        id: 4,
        desde: { nombre: 'q1', id: 1 },
        hacia: { nombre: 'q2', id: 2 },
        leer: '△',
        escribir: '△',
        direccion: 'L',
      },
      {
        id: 5,
        desde: { nombre: 'q2', id: 2 },
        hacia: { nombre: 'q2', id: 2 },
        leer: '0',
        escribir: '0',
        direccion: 'L',
      },
      {
        id: 6,
        desde: { nombre: 'q2', id: 2 },
        hacia: { nombre: 'q2', id: 2 },
        leer: '1',
        escribir: '1',
        direccion: 'L',
      },
      {
        id: 7,
        desde: { nombre: 'q2', id: 2 },
        hacia: { nombre: 'qf', id: 3 },
        leer: '#',
        escribir: '#',
        direccion: 'N',
      },
    ],
  },
  {
    descripcion: 'Suma 1 a un número binario',
    estados: [
      { nombre: 'q0', id: 0 },
      { nombre: 'q1', id: 1 },
      { nombre: 'qf', id: 2 },
    ],
    alfabeto: ['1', '0'],
    blanco: '△',
    estadoFinal: { nombre: 'qf', id: 2 },
    estadoInicial: { nombre: 'q0', id: 0 },
    transiciones: [
      {
        id: 0,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q0', id: 0 },
        leer: '1',
        escribir: '1',
        direccion: 'R',
      },
      {
        id: 1,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q0', id: 0 },
        leer: '0',
        escribir: '0',
        direccion: 'R',
      },
      {
        id: 2,
        desde: { nombre: 'q0', id: 0 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '△',
        escribir: '△',
        direccion: 'L',
      },
      {
        id: 3,
        desde: { nombre: 'q1', id: 1 },
        hacia: { nombre: 'q1', id: 1 },
        leer: '1',
        escribir: '0',
        direccion: 'L',
      },
      {
        id: 4,
        desde: { nombre: 'q1', id: 1 },
        hacia: { nombre: 'qf', id: 2 },
        leer: '0',
        escribir: '1',
        direccion: 'L',
      },
      {
        id: 5,
        desde: { nombre: 'q1', id: 1 },
        hacia: { nombre: 'qf', id: 2 },
        leer: '△',
        escribir: '1',
        direccion: 'L',
      },
    ],
  },
];
